version: "3.12"
services:
  db:
    image: postgres:16
    ports:
      - "4569:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo16-db1-data:/var/lib/postgresql/data 
    
  odoo_web:
    image: odoo:16
   
    ports:
      - "9502:8069"
    volumes:
      - ./T-box:/T-box
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo16-web-data:/var/lib/odoo
    #command:
      #-d db_name 
      #--update all
      

volumes:
  odoo16-web-data:
  odoo16-db1-data:


